name: Unit

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test:
        name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version:
                    - 20
                    - 19
                    - 18
                    - 17
                    - 16
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm
            - run: npm ci
            - run: npm test
